// src/components/CityForm.vue
<template>
  <div class="form-horizontal">
    <!-- City field -->
    <div class="form-group">
      <label class="control-label col-md-3">City</label>
      <div class="col-md-9">
        <input
          type="text"
          class="form-control"
          v-model="city"
          placeholder="Enter city (e.g. London)"
        />
      </div>
    </div>

    <!-- Country field -->
    <div class="form-group">
      <label class="control-label col-md-3">Country</label>
      <div class="col-md-9">
        <Countries :onChange="updateCountry" />
      </div>
    </div>

    <!-- Submit button -->
    <div class="form-group">
      <div class="col-md-10 col-md-offset-2">
        <button class="btn btn-default" @click="search">Search</button>
      </div>
    </div>
  </div>
</template>

<script>
import Vue from 'vue'
import Countries from './Countries.vue'

export default Vue.component('city-form', {
  name: 'CityForm',

  components: {
    Countries
  },

  data: () => ({
    city: '',
    country: ''
  }),

  props: {
    searchCallback: Function
  },

  methods: {
    search: function () {
      if (!this.hasInvalidFields()) {
        this.searchCallback(this.city, this.country)
      }
    },

    hasInvalidFields: function () {
      return (this.city === '' || this.country === '')
    },

    updateCountry: function (ev) {
      this.country = ev.target.value
    }
  }
})
</script>

// src/components/CityForm.jsx
import React, { Component } from 'react'

class CityForm extends Component {
  constructor(props) {
    super(props)
    this.callback = this.callback.bind(this)
  }

  callback() {
    const { props, cityField, countryField } = this

    props.searchCallback(
      cityField.value,
      countryField.value
    )
  }

  render() {
    const style = {
      display: (this.props.isVisible ? 'block' : 'none')
    }

    return (
      <div className="form-horizontal" style={style}>
        { /* City field */ }
        <div className="form-group">
          <label className="control-label col-md-3">City:</label>
          <div className="col-md-9">
            <input ref={(input) => this.cityField = input} type="text" className="form-control" placeholder="Enter city (e.g. London)" />
          </div>
        </div>

        { /* Country field */ }
        <div className="form-group">
          <label className="control-label col-md-3">Country Code:</label>
          <div className="col-md-9">
            <input ref={(input) => this.countryField = input} type="text" className="form-control" placeholder="Enter country code (e.g. UK)" />
          </div>
        </div>

        { /* Submit button */ }
        <div className="form-group">
          <div className="col-md-10 col-md-offset-2">
            <button onClick={this.callback} className="btn btn-default">Search</button>
          </div>
        </div>
      </div>
    );
  }
}

export default CityForm
