// src/components/FormSelector.vue
<template>
  <div class="form-group">
    <div class="btn-group btn-group-lg btn-group-justified">
      <div class="btn-group">
        <button
          type="button"
          class="btn btn-default active"
          :class="{ active: isCityActive }"
          @click="activateCityForm"
        >
          Search by City
        </button>
      </div>

      <div class="btn-group">
        <button
          type="button"
          class="btn btn-default active"
          :class="{ active: isGeolocActive }"
          @click="activateGeolocForm"
        >
          Search by City
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'FormSelector',

  props: {
    isCityActive: Boolean,
    isGeolocActive: Boolean,
    activateCityForm: Function,
    activateGeolocForm: Function
  }
})
</script>

// src/components/FormSelector.jsx
import React from 'react'

const classNames = require('classnames')

const FormSelector = ({isCityActive, isGeolocActive, activateCityForm, activateGeolocForm}) => {
  const cityButtonStyle = classNames('btn', 'btn-default', 'cityFormBtn', { 'active': isCityActive })
  const geolocButtonStyle = classNames('btn', 'btn-default', 'geolocFormBtn', { 'active': isGeolocActive })

  return (
    <div className="form-group">
      <div className="btn-group btn-group-lg btn-group-justified">
        <div className="btn-group">
          <button type="button" className={cityButtonStyle} onClick={activateCityForm}>
              Search by City
          </button>
        </div>
        <div className="btn-group">
          <button type="button" className={geolocButtonStyle} onClick={activateGeolocForm}>Search by Geolocation</button>
        </div>
      </div>
    </div>
  )
}

export default FormSelector
